# Permalinks
permalink:           pretty

# Setup
title:               Protozoa Test
tagline:             A Single Celled Organism for Education
url:                 http://cel.fscj.edu
baseurl:             ""
infectionVersion:    release 1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass

# About/contact
author:
  name:              Ian Vanhoof
  url:               https://twitter.com/ianvanhoof
  email:             vanhoof.ian@gmail.com
exclude: [.gitignore,/.git,/_programTemplates,htaccess.txt,README.md,/_slideTemplates,/widgets]
include: [.htaccess]
#------ Google Font Links
googlefontLink: <link href='https://fonts.googleapis.com/css?family=Oswald:400,300,700|Quattrocento' rel='stylesheet' type='text/css'>

